name: Publish

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Run only if tests succeeded
    environment: master
    permissions:
      id-token: write
    steps:
      # retrieve your distributions here
      - uses: actions/checkout@v2

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: src/
